package com.mapper;

import com.model.Dept;
import com.model.DeptExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    long countByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    int deleteByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    int insert(Dept row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    int insertSelective(Dept row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    List<Dept> selectByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    Dept selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    int updateByExampleSelective(@Param("row") Dept row, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    int updateByExample(@Param("row") Dept row, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    int updateByPrimaryKeySelective(Dept row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    int updateByPrimaryKey(Dept row);
}