package com.model;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPT.DEPT_ID
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPT.DEPT_NAME
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPT.DEPT_ID
     *
     * @return the value of DEPT.DEPT_ID
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPT.DEPT_ID
     *
     * @param deptId the value for DEPT.DEPT_ID
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPT.DEPT_NAME
     *
     * @return the value of DEPT.DEPT_NAME
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPT.DEPT_NAME
     *
     * @param deptName the value for DEPT.DEPT_NAME
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
}