package com.model;

import java.util.Date;
//Project
public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.PROJECT_ID
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.PROJECT_NAME
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.DEPT_ID
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.DIFFICULTY
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    private String difficulty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.INS_TM
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    private Date insTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.UPD_TM
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    private Date updTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.VERSION
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.LOCATION
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.PROJECT_ID
     *
     * @return the value of PROJECT.PROJECT_ID
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.PROJECT_ID
     *
     * @param projectId the value for PROJECT.PROJECT_ID
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.PROJECT_NAME
     *
     * @return the value of PROJECT.PROJECT_NAME
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.PROJECT_NAME
     *
     * @param projectName the value for PROJECT.PROJECT_NAME
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.DEPT_ID
     *
     * @return the value of PROJECT.DEPT_ID
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.DEPT_ID
     *
     * @param deptId the value for PROJECT.DEPT_ID
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.DIFFICULTY
     *
     * @return the value of PROJECT.DIFFICULTY
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public String getDifficulty() {
        return difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.DIFFICULTY
     *
     * @param difficulty the value for PROJECT.DIFFICULTY
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public void setDifficulty(String difficulty) {
        this.difficulty = difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.INS_TM
     *
     * @return the value of PROJECT.INS_TM
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public Date getInsTm() {
        return insTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.INS_TM
     *
     * @param insTm the value for PROJECT.INS_TM
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public void setInsTm(Date insTm) {
        this.insTm = insTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.UPD_TM
     *
     * @return the value of PROJECT.UPD_TM
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public Date getUpdTm() {
        return updTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.UPD_TM
     *
     * @param updTm the value for PROJECT.UPD_TM
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public void setUpdTm(Date updTm) {
        this.updTm = updTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.VERSION
     *
     * @return the value of PROJECT.VERSION
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.VERSION
     *
     * @param version the value for PROJECT.VERSION
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.LOCATION
     *
     * @return the value of PROJECT.LOCATION
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.LOCATION
     *
     * @param location the value for PROJECT.LOCATION
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public void setLocation(String location) {
        this.location = location;
    }

	public Project(Integer projectId, String projectName, Integer deptId, String difficulty, Date insTm, Date updTm,
			Integer version, String location) {
		super();
		this.projectId = projectId;
		this.projectName = projectName;
		this.deptId = deptId;
		this.difficulty = difficulty;
		this.insTm = insTm;
		this.updTm = updTm;
		this.version = version;
		this.location = location;
	}
	
	
    
    
}