package com.model;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.id
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.username
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.password
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.authority
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    private String authority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.email
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.id
     *
     * @return the value of USERS.id
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.id
     *
     * @param id the value for USERS.id
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.username
     *
     * @return the value of USERS.username
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.username
     *
     * @param username the value for USERS.username
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.password
     *
     * @return the value of USERS.password
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.password
     *
     * @param password the value for USERS.password
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.authority
     *
     * @return the value of USERS.authority
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.authority
     *
     * @param authority the value for USERS.authority
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public void setAuthority(String authority) {
        this.authority = authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.email
     *
     * @return the value of USERS.email
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.email
     *
     * @param email the value for USERS.email
     *
     * @mbg.generated Wed Jun 14 15:59:59 ICT 2023
     */
    public void setEmail(String email) {
        this.email = email;
    }
}